manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: antoinegs
      url-base: https://github.com/AntoineGS
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: m165437
      url-base: https://github.com/M165437
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    - name: zmk-pmw3610-driver
      revision: main
      path: modules/drivers/zmk-pmw3610-driver
      remote: antoinegs
    - name: mario-peripheral-animation
      remote: gpeye
      revision: main
    - name: nice-view-gem
      remote: m165437
      revision: main
  self:
    path: config
